version: "3.9"
services:
  web-server:
    container_name: "web-server"
    command: cargo watch -x 'run'
    build:
        dockerfile: Dockerfile.dev
        context: .
        cache_from:
          - rust:1.54
    links:
      - postgres
    environment:
      - USER=dev
      - PG_URL=postgresql://postgres:docker@postgres:5432/p2boards?sslmode=disable
      - PG_POOL_SIZE=10
    networks:
      - boards-network
    depends_on:
      - postgres
    tty: true
    volumes: 
      - type: bind
        source: ./server
        target: /server
    ports:
      - "8080:8080"

  postgres:
    build:
      dockerfile: Dockerfile.db
      context: .
    environment:
      POSTGRES_PASSWORD: "docker"
    networks:
      - boards-network
    ports:
      - "5432:5432"
  
  dbmate:
    build:
      context: .
      dockerfile: Dockerfile.dbmate
    command:
      - ls
      - create_db.sh
    environment:
        DATABASE_URL: "postgresql://postgres:docker@postgres:5432/p2boards?sslmode=disable"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - boards-network
    volumes:
      - ./db:/db
    
networks:
  boards-network:
    driver: bridge