version: "3.9"
services:
  web-server:
    container_name: "web-server"
    build: ./server
    command: cargo watch -x 'run'
    depends_on:
      - postgres
    env_file:
      ./server/.env.entrypoint.dev
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./server/container-volume
        target: /opt/server
      - type: volume
        source: cargo_home
        target: /opt/cargo


  postgres:
    build: ./db
    environment:
      - POSTGRES_DB=p2boards
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  cargo_home:
  postgres_data: