version: "3.9"
services:
  web-server:
    container_name: "web-server"
    command: cargo watch -x 'run'
    build:
      dockerfile: Dockerfile.server
      context: .
      cache_from:
        - rust:1.54
    depends_on:
      - postgres
    links:
      - postgres
    environment: 
    - DATABASE_URL=postgresql://docker:docker@localhost:5432/p2boards
    - SERVER.HOST=0.0.0.0
    - SERVER.PORT=8080
    - PROOF.DEMO=80
    - PROOF.VIDEO=100
    volumes: 
        - ./server:/server
    ports:
      - "8080:8080"



  postgres:
    build:
      dockerfile: Dockerfile.db
      context: .
    environment:
      - POSTGRES_DB=p2boards
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    restart: always
    ports:
      - "5432:5432"
