[package]
name = "server"
version = "0.1.0"
authors = ["Daniel Bates <36864021+DanielBatesJ@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#actix-web = "3"
actix-web = "3.3.2"
#actix-rt = "2.0.0"
actix-rt = "2.2.0"
actix-cors = "0.5.4"
futures-util = "0.3.13"

diesel = { version = "1.4.4", features = ["mysql", "chrono", "r2d2"] }
chrono = { version = "0.4.19", features = ["serde", "rustc-serialize"] }

serde = "1.0.123"
serde_json = "1.0.64"
serde_derive = "1.0.123"

dotenv = "0.15.0"
config = "0.11.0"
num = "0.1.42"
env_logger = "0.8.3"

# Might need to run $ sudo apt-get install pkg-config libssl-dev
#r2d2 = "0.8.9"
#r2d2_mysql = "18.0.0"
#r2d2-diesel = "1.0.0"