[package]
name = "server"
version = "0.1.0"
authors = ["Daniel Bates <36864021+DanielBatesJ@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "2.0.0"
serde = "1.0"
serde_json = "1.0"
dotenv = "0.15.0"
config = "0.11.0"